class BannerDetailsModel {
  String projectID,
      title,
      description,
      address,
      projectUnitID,
      mainFeaturesInternetAccess,
      mainFeaturesSatelliteORCableTV,
      mainFeaturesElectricityBackup,
      plotPossesion,
      nearbySchool,
      plotElectricity,
      nearbyHospital,
      plotSuiGas,
      plotBoundaryWall,
      nearbyShoppingMall,
      plotParkFacing,
      plotCorner,
      neabyRestaurant,
      plotWaterSupply,
      plotSewerage,
      nearbyPublicTransportService,
      otherNearbyPlace,
      lawnorGarden,
      maintenanceStaff,
      swimmingPool,
      securityStaff,
      categoryTypeID,
      categoryTypeName,
      startPrice,
      endPrice,
      priceDetails,
      currencyType,
      bsid,
      countryID,
      countryName,
      cityID,
      cityName,
      locationID,
      locationName,
      imageName,
      agentID,
      agentName,
      agentDescription,
      agentGender,
      agentPhoneNo,
      agentAddress,
      agentPosition,
      agentEmail,
      agentImage,
      propertyHolder;

  int bedroom, bathroom, garage, hall, kitchen, floors, viewCount, days;

  BannerDetailsModel({
    this.projectID,
    this.title,
    this.description,
    this.address,
    this.projectUnitID,
    this.bedroom,
    this.bathroom,
    this.garage,
    this.hall,
    this.kitchen,
    this.floors,
    this.viewCount,
    this.mainFeaturesInternetAccess,
    this.mainFeaturesSatelliteORCableTV,
    this.mainFeaturesElectricityBackup,
    this.plotPossesion,
    this.nearbySchool,
    this.plotElectricity,
    this.nearbyHospital,
    this.plotSuiGas,
    this.plotBoundaryWall,
    this.nearbyShoppingMall,
    this.plotParkFacing,
    this.plotCorner,
    this.neabyRestaurant,
    this.plotWaterSupply,
    this.plotSewerage,
    this.nearbyPublicTransportService,
    this.otherNearbyPlace,
    this.lawnorGarden,
    this.maintenanceStaff,
    this.swimmingPool,
    this.securityStaff,
    this.categoryTypeID,
    this.categoryTypeName,
    this.startPrice,
    this.endPrice,
    this.priceDetails,
    this.currencyType,
    this.bsid,
    this.countryID,
    this.countryName,
    this.cityID,
    this.cityName,
    this.locationID,
    this.locationName,
    this.imageName,
    this.days,
    this.agentID,
    this.agentName,
    this.agentDescription,
    this.agentGender,
    this.agentPhoneNo,
    this.agentAddress,
    this.agentPosition,
    this.agentEmail,
    this.agentImage,
    this.propertyHolder,
  });

  factory BannerDetailsModel.fromJson(Map<String, dynamic> json) {
    return BannerDetailsModel(
      projectID: json['projectID'] == null ? '' : json['projectID'],
      title: json['title'] == null ? '' : json['title'],
      description: json['description'] == null ? '' : json['description'],
      address: json['address'] == null ? '' : json['address'],
      projectUnitID: json['projectUnitID'] == null ? '' : json['projectUnitID'],
      bedroom: json['bedroom'] == null ? '' : json['bedroom'],
      bathroom: json['bathroom'] == null ? '' : json['bathroom'],
      garage: json['garage'] == null ? '' : json['garage'],
      hall: json['hall'] == null ? '' : json['hall'],
      kitchen: json['kitchen'] == null ? '' : json['kitchen'],
      floors: json['floors'] == null ? '' : json['floors'],
      viewCount: json['viewCount'] == null ? '' : json['viewCount'],
      mainFeaturesInternetAccess: json['mainFeaturesInternetAccess'] == null
          ? ''
          : json['mainFeaturesInternetAccess'],
      mainFeaturesSatelliteORCableTV:
          json['mainFeaturesSatelliteORCableTV'] == null
              ? ''
              : json['mainFeaturesSatelliteORCableTV'],
      mainFeaturesElectricityBackup:
          json['mainFeaturesElectricityBackup'] == null
              ? ''
              : json['mainFeaturesElectricityBackup'],
      plotPossesion: json['plotPossesion'] == null ? '' : json['plotPossesion'],
      nearbySchool: json['nearbySchool'] == null ? '' : json['nearbySchool'],
      plotElectricity:
          json['plotElectricity'] == null ? '' : json['plotElectricity'],
      nearbyHospital:
          json['nearbyHospital'] == null ? '' : json['nearbyHospital'],
      plotSuiGas: json['plotSuiGas'] == null ? '' : json['plotSuiGas'],
      plotBoundaryWall:
          json['plotBoundaryWall'] == null ? '' : json['plotBoundaryWall'],
      nearbyShoppingMall:
          json['nearbyShoppingMall'] == null ? '' : json['nearbyShoppingMall'],
      plotParkFacing:
          json['plotParkFacing'] == null ? '' : json['plotParkFacing'],
      plotCorner: json['plotCorner'] == null ? '' : json['plotCorner'],
      neabyRestaurant:
          json['nearbyRestaurants'] == null ? '' : json['nearbyRestaurants'],
      plotWaterSupply:
          json['plotWaterSupply'] == null ? '' : json['plotWaterSupply'],
      plotSewerage: json['plotSewerage'] == null ? '' : json['plotSewerage'],
      nearbyPublicTransportService: json['nearbyPublicTransportService'] == null
          ? ''
          : json['nearbyPublicTransportService'],
      otherNearbyPlace:
          json['otherNearbyPlace'] == null ? '' : json['otherNearbyPlace'],
      lawnorGarden: json['lawnorGarden'] == null ? '' : json['lawnorGarden'],
      maintenanceStaff:
          json['maintenanceStaff'] == null ? '' : json['maintenanceStaff'],
      swimmingPool: json['swimmingPool'] == null ? '' : json['swimmingPool'],
      securityStaff: json['securityStaff'] == null ? '' : json['securityStaff'],
      categoryTypeID:
          json['categoryTypeID'] == null ? '' : json['categoryTypeID'],
      categoryTypeName:
          json['categoryTypeName'] == null ? '' : json['categoryTypeName'],
      startPrice: json['startPrice'] == null ? '' : json['startPrice'],
      endPrice: json['endPrice'] == null ? '' : json['endPrice'],
      priceDetails: json['priceDetails'] == null ? '' : json['priceDetails'],
      currencyType: json['currencyType'] == null ? '' : json['currencyType'],
      bsid: json['bsid'] == null ? '' : json['bsid'],
      countryID: json['countryID'] == null ? '' : json['countryID'],
      countryName: json['countryName'] == null ? '' : json['countryName'],
      cityID: json['cityID'] == null ? '' : json['cityID'],
      cityName: json['cityName'] == null ? '' : json['cityName'],
      locationID: json['locationID'] == null ? '' : json['locationID'],
      locationName: json['locationName'] == null ? '' : json['locationName'],
      imageName: json['imageName'] == null ? '' : json['imageName'],
      days: json['days'] == null ? '' : json['days'],
      agentID: json['agentID'] == null ? '' : json['agentID'],
      agentName: json['agentName'] == null ? '' : json['agentName'],
      agentDescription:
          json['agentDescription'] == null ? '' : json['agentDescription'],
      agentGender: json['agentGender'] == null ? '' : json['agentGender'],
      agentPhoneNo: json['agentPhoneNo'] == null ? '' : json['agentPhoneNo'],
      agentAddress: json['agentAddress'] == null ? '' : json['agentAddress'],
      agentPosition: json['agentPosition'] == null ? '' : json['agentPosition'],
      agentEmail: json['agentEmail'] == null ? '' : json['agentEmail'],
      agentImage: json['agentImage'] == null ? '' : json['agentImage'],
    );
  }
}
